In [3]:
#conda install pytorch torchvision torchaudio -c pytorch -y

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/gyeongdeokpark/opt/anaconda3

  added / updated specs:
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-2.0.0              |          py3.9_0        76.4 MB  pytorch
    torchaudio-2.0.0           |         py39_cpu         6.6 MB  pytorch
    torchvision-0.15.0         |         py39_cpu         6.4 MB  pytorch
    ------------------------------------------------------------
                                           Total:        89.5 MB

The following NEW packages will be INSTALLED:

  ffmpeg             pytorch/osx-64::ffmpeg-4.3-h0a44026_0 None
  gnutls             pkgs

In [5]:
# pytorch import 
import torch
# check version
print(torch.__version__)

2.0.0


### Scala: ZeroDimension Tensor

In [73]:
import numpy as np
data0 = np.array(10)
print(data0, data0.ndim, data0.shape)

10 0 ()


### Vector: One Dimension Tensor

In [46]:
data1 = torch.FloatTensor([1, 2])
print(data1, data1.dim(), data1.shape)

tensor([1., 2.]) 1 torch.Size([2])


In [48]:
data1 = torch.FloatTensor(3)
print(data1, data1.dim(), data1.shape)

tensor([0., 0., 0.]) 1 torch.Size([3])


### Matrix:

#### 2D Tensor

In [37]:
data2 = torch.rand(5,9)fi
print(data2, data2.dim(), data2.shape)

tensor([[5.6514e-01, 7.6482e-01, 7.1869e-01, 6.8475e-01, 8.4244e-01, 1.8723e-01,
         5.8109e-01, 2.1734e-01, 7.3604e-01],
        [1.6300e-01, 3.9504e-01, 3.0982e-01, 6.8726e-01, 3.7568e-03, 4.1115e-01,
         4.1774e-01, 5.7040e-01, 3.3384e-01],
        [2.0237e-03, 9.3498e-03, 4.5884e-04, 9.3843e-01, 3.8153e-02, 3.4664e-01,
         2.0660e-01, 6.2135e-01, 8.2283e-01],
        [2.6230e-01, 8.8346e-01, 3.9650e-01, 9.7011e-01, 8.0028e-01, 7.2706e-02,
         1.8863e-01, 1.4509e-01, 9.8381e-01],
        [4.7607e-01, 9.8306e-01, 5.0544e-02, 9.9563e-01, 7.9161e-01, 8.0645e-01,
         9.9257e-02, 3.0215e-01, 7.9286e-01]]) 2 torch.Size([5, 9])


#### 3D Tensor

In [39]:
data3 = torch.rand(3, 2, 1)
print(data3, data3.dim(), data3.shape)

tensor([[[0.0493],
         [0.8115]],

        [[0.6462],
         [0.9108]],

        [[0.5997],
         [0.9462]]]) 3 torch.Size([3, 2, 1])


In [40]:
data3 = torch.FloatTensor([[[1],[2]],[[3],[4]],[[5],[6]]])
print(data3, data3.dim(), data3.shape)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 torch.Size([3, 2, 1])


### Tensor Reshape

In [41]:
data = torch.DoubleTensor([[1,2,3],[4,5,6]])
print(data, data.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])


In [42]:
data = data.reshape(3,2)
print(data, data.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64) torch.Size([3, 2])


In [44]:
data = data.reshape(2, -1)
print(data, data.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])


#### View

In [53]:
data = torch.DoubleTensor([ 
    [[1, 2, 3], 
    [4, 5, 6]],
    [[7, 8, 9], 
    [10, 11, 12]]
])
print (data.shape, data.size(0), data.size(1), data.size(2))

torch.Size([2, 2, 3]) 2 2 3


In [54]:
data = data.view(3, -1) 
print (data, data.shape)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64) torch.Size([3, 4])


In [55]:
data = data.view(-1, 3)
print (data, data.shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64) torch.Size([4, 3])


In [62]:
data = data.view(3, 4, -1)
print (data, data.shape)

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.],
         [12.]]], dtype=torch.float64) torch.Size([3, 4, 1])


In [68]:
data = torch.FloatTensor([[1], [2], [3], [4]])
print(data, data.ndim, data.shape)
data1 = torch.squeeze(data)
print(data1, data1.ndim, data1.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.]]) 2 torch.Size([4, 1])
tensor([1., 2., 3., 4.]) 1 torch.Size([4])


In [72]:
data = torch.FloatTensor([[1,2], [3,4]])
print(data, data.ndim, data.shape)
data1 = data.unsqueeze(0)
print(data1, data1.ndim, data1.shape)
data2 = data.unsqueeze(1)
print(data2, data2.ndim, data2.shape)
data3 = data.unsqueeze(2)
print(data3, data3.ndim, data3.shape)

tensor([[1., 2.],
        [3., 4.]]) 2 torch.Size([2, 2])
tensor([[[1., 2.],
         [3., 4.]]]) 3 torch.Size([1, 2, 2])
tensor([[[1., 2.]],

        [[3., 4.]]]) 3 torch.Size([2, 1, 2])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) 3 torch.Size([2, 2, 1])
