In [1]:
import torch
import numpy as np

In [3]:
tensor1 = torch.full((3, 3), 4)
tensor2 = torch.full((3, 3), 2)
print(tensor1)
print(tensor2)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])


In [6]:
print(tensor1 + tensor2)
print(tensor1 - tensor2)
print(tensor1 * tensor2)
print(tensor1 / tensor2)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [7]:
torch.matmul(tensor1, tensor2)

tensor([[24, 24, 24],
        [24, 24, 24],
        [24, 24, 24]])

In [8]:
tensor1 = torch.full((4, 2), 4)
tensor2 = torch.full((2, 3), 2)
torch.matmul(tensor1, tensor2)

tensor([[16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16]])

broadcasting

In [27]:
tensor1 = torch.FloatTensor(10, 20, 4)
tensor2 = torch.FloatTensor(10, 1, 4)
tensor = tensor1 + tensor2
print(tensor1.shape, tensor2.shape, tensor.shape)

torch.Size([10, 20, 4]) torch.Size([10, 1, 4]) torch.Size([10, 20, 4])


In [29]:
tensor1 = torch.FloatTensor(5, 7, 3)
tensor2 = torch.FloatTensor(1, 1, 3)
tensor = tensor1 + tensor2
print(tensor1.shape, tensor2.shape, tensor.shape)

torch.Size([5, 7, 3]) torch.Size([1, 1, 3]) torch.Size([5, 7, 3])


#### Indexing

In [32]:
tensor = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(tensor)
print(tensor[1, 1])
print(tensor[:, 1])
print(tensor[:, :])
print(tensor[:])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(5.)
tensor([2., 5.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [34]:
tensor1 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(tensor1)
tensor2 = tensor1[:2, :2]
print(tensor2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])


In [36]:
tensor2[1, 1] = 0
print(tensor1)
print(tensor2)

tensor([[1., 2., 3.],
        [4., 0., 6.]])
tensor([[1., 2.],
        [4., 0.]])


In [37]:
tensor1 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(tensor1)
tensor2 = tensor1[:2, :2].clone().detach()
print(tensor2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])


In [38]:
tensor2[1, 1] = 0
print(tensor1)
print(tensor2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 0.]])
