In [2]:
import torch
import numpy as np

#### Indexing

In [3]:
tensor = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(tensor)
print(tensor[1, 1])
print(tensor[:, 1])
print(tensor[:, :])
print(tensor[:])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(5.)
tensor([2., 5.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
tensor1 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(tensor1)
tensor2 = tensor1[:2, :2]
print(tensor2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])


In [5]:
tensor2[1, 1] = 0
print(tensor1)
print(tensor2)

tensor([[1., 2., 3.],
        [4., 0., 6.]])
tensor([[1., 2.],
        [4., 0.]])


In [6]:
tensor1 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(tensor1)
tensor2 = tensor1[:2, :2].clone().detach()
print(tensor2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])


In [7]:
tensor2[1, 1] = 0
print(tensor1)
print(tensor2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 0.]])


In [18]:
tensor1 = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7, 8])
index = torch.where(tensor1 < 3)
print(index)
print(tensor1[index])

(tensor([0, 1]),)
tensor([1., 2.])


In [20]:
tensor2 = torch.where(tensor1 < 4, -1, 1)
print(tensor2)

tensor([-1, -1, -1,  1,  1,  1,  1,  1])


In [21]:
tensor = torch.FloatTensor([[1,2,3], [4,5,6]])
print(tensor.min())
print(tensor.max())
print(tensor.sum())
print(tensor.mean())
print(tensor.var())
print(tensor.std())
print(tensor.argmin())
print(tensor.argmax())

tensor(1.)
tensor(6.)
tensor(21.)
tensor(3.5000)
tensor(3.5000)
tensor(1.8708)
tensor(0)
tensor(5)


In [22]:
tensor = torch.linspace(1, 5, 4)
print(tensor)

tensor([1.0000, 2.3333, 3.6667, 5.0000])


In [23]:
torch.save(tensor, "my_first_tensor")

In [24]:
load_tensor = torch.load("my_first_tensor")
print(load_tensor)

tensor([1.0000, 2.3333, 3.6667, 5.0000])


In [28]:
tensor1 = torch.linspace(2, 4, 4)
tensor2 = torch.linspace(3, 5, 5)
tensor3 = torch.linspace(5, 8, 6)
print(tensor1)
print(tensor2)
print(tensor3)
tensorsets = {"data1": tensor1, "data2": tensor2, "data3": tensor3}
torch.save(tensorsets, "tensor_datasets")

tensor([2.0000, 2.6667, 3.3333, 4.0000])
tensor([3.0000, 3.5000, 4.0000, 4.5000, 5.0000])
tensor([5.0000, 5.6000, 6.2000, 6.8000, 7.4000, 8.0000])


In [27]:
datasets = torch.load("tensor_datasets")
print(datasets["data1"])
print(datasets["data2"])
print(datasets["data3"])

tensor([2.0000, 2.6667, 3.3333, 4.0000])
tensor([3.0000, 3.5000, 4.0000, 4.5000, 5.0000])
tensor([5.0000, 5.6000, 6.2000, 6.8000, 7.4000, 8.0000])
