In [1]:
import numpy as np

In [2]:
data1 = [1,2,3]
data2 = [4,5,6]

data1 + data2

[1, 2, 3, 4, 5, 6]

In [3]:
data1 = np.array([1, 2, 3])
print(data1, type(data1))

[1 2 3] <class 'numpy.ndarray'>


In [4]:
data1.shape

(3,)

In [5]:
data1.ndim

1

In [6]:
data1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data1.shape, data1.ndim)

(3, 3) 2


In [7]:
print(data1.dtype)

int64


In [8]:
print(data1.size)

9


In [11]:
data1 = np.array([1, 2, 3, 4, 5, 6])
print(data1)
data1 = data1.reshape(3, 2)
print(data1)
data1 = data1.reshape(3, -1)
print(data1)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
