In [5]:
import torch
import torch.nn as nn

In [48]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.w = torch.FloatTensor(5, 4)
        self.b = torch.FloatTensor(4)
        
    def forward(self, x):
        y = torch.matmul(x, self.w) + self.b
        return y

In [49]:
x = torch.FloatTensor(5)
linear = NeuralNetwork()
y = linear(x)

In [50]:
print(y, y.shape)

tensor([0., 0., 0., 0.]) torch.Size([4])


In [34]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.w = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
    def forward(self, x):
        y = torch.matmul(x, self.w) + self.b
        return y

In [35]:
x = torch.FloatTensor(4)
linear = NeuralNetwork(4, 3)
y = linear(x)
print(y, y.shape)
for param in linear.parameters():
    print(param)

tensor([0., 0., 0.], grad_fn=<AddBackward0>) torch.Size([3])
Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [36]:
linear = nn.Linear(4,3)
y = linear(x)
print(y, y.shape)

for param in linear.parameters():
    print(param)

tensor([-0.3226,  0.2762, -0.2769], grad_fn=<AddBackward0>) torch.Size([3])
Parameter containing:
tensor([[ 0.2820,  0.3209, -0.0670,  0.3630],
        [ 0.0289, -0.3504,  0.0065, -0.2226],
        [-0.4002,  0.4889,  0.4082, -0.4126]], requires_grad=True)
Parameter containing:
tensor([-0.3226,  0.2762, -0.2769], requires_grad=True)
