In [1]:
import torch
import torch.nn as nn

In [2]:
class Linear_Model(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, 10)
        self.linear2 = nn.Linear(10, 10)
        self.linear3 = nn.Linear(10, 10)
        self.linear4 = nn.Linear(10, 10)
        self.linear5 = nn.Linear(10, output_dim)
        self.activation = nn.LeakyReLU(0.1)
    
    def forward(self, x):
        hidden = self.activation(self.linear1(x))
        hidden = self.activation(self.linear2(hidden))
        hidden = self.activation(self.linear3(hidden))
        hidden = self.activation(self.linear4(hidden))
        y = self.linear5(hidden)
        
        return y

In [3]:
x = torch.ones(4)
y = torch.zeros(3)
model = Linear_Model(4, 3)
loss_function = nn.MSELoss()

In [4]:
learning_rate = 0.01
epochs = 1000 
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs + 1):

    y_pred = model(x)
    loss = loss_function(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [5]:
print(loss)
for param in model.parameters():
    print (param)

tensor(1.2077e-12, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.0827, -0.1349, -0.0421,  0.3846],
        [ 0.1337,  0.4097,  0.1397,  0.1425],
        [-0.1879,  0.4310,  0.2176, -0.0887],
        [ 0.4628,  0.3231, -0.0307,  0.2690],
        [ 0.4264, -0.0583,  0.4971, -0.3086],
        [ 0.1295,  0.4308,  0.2564,  0.1666],
        [-0.0149,  0.1241,  0.4024,  0.0560],
        [ 0.1743, -0.4020,  0.4093, -0.0639],
        [-0.0122,  0.0788, -0.2221, -0.1275],
        [-0.4992,  0.0131,  0.4991, -0.1829]], requires_grad=True)
Parameter containing:
tensor([ 0.4505, -0.2977,  0.1294,  0.1382,  0.0276, -0.0328,  0.4891,  0.4361,
        -0.0122,  0.1041], requires_grad=True)
Parameter containing:
tensor([[ 0.0552,  0.0888, -0.1886, -0.2194, -0.0082, -0.1824, -0.2840, -0.1082,
          0.0392,  0.2787],
        [ 0.1223, -0.2209, -0.2674, -0.3003, -0.1725,  0.0326,  0.2187, -0.3127,
          0.2965,  0.0893],
        [ 0.2291,  0.0446,  0.2998,  0.1310, -0.1256, -0.1406